=== cgeorgy29/Git_FIA4/Corentin/SOA/nuages.dtd
<!ELEMENT nuages (nuage*)>
<!ELEMENT nuage (variete, especes, altitudes)>
<!ATTLIST nuage hydrometeore (oui | non) #IMPLIED>
<!ELEMENT variete (#PCDATA)>
<!ELEMENT especes (espece+)>
<!ELEMENT espece (#PCDATA)>
<!ATTLIST espece type CDATA #IMPLIED>
<!ELEMENT altitudes (min,max)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ATTLIST min unite CDATA "m">
<!ATTLIST max unite CDATA "m">

=== cgeorgy29/Git_FIA4/Corentin/SOA/TD XML/Exo2.xml
<!DOCTYPE nuages SYSTEM "nuages.dtd" >
<nuages>
    <nuage hydrometeore="oui">
        <variete>Cumulonimbus</variete>
        <especes>
            <espece>calvus</espece>
            <espece>capilatus</espece>
            <espece type="gros">mamatus</espece>
        </especes>
        <altitudes>
            <min unite="m">300</min>
            <max unite="m">18000</max>
        </altitudes>
    </nuage>
    <nuage hydrometeore="non">
        <variete>Altocumulus</variete>
        <especes>
            <espece>calvus</espece>
            <espece>lenticularis</espece>
            <espece>capilatus</espece>
            <espece type="gros">mamatus</espece>
        </especes>
        <altitudes>
            <min unite="m">500</min>
            <max unite="m">15000</max>
        </altitudes>
    </nuage>
</nuages>
