=== cgeorgy29/Git_FIA4/Corentin/SOA/TP/TP1/enseignants.dtd
<!ELEMENT enseignants (enseignant+)>
<!ELEMENT enseignant (nom, prenom+, age*) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT age (#PCDATA) >
<!ATTLIST enseignant
dep CDATA #REQUIRED
>
<!ATTLIST enseignants annÃ©e CDATA #IMPLIED>
<!ENTITY dep "ISIS" >

=== cgeorgy29/Git_FIA4/Corentin/SOA/TP/TP1/enseignants.xml
<!DOCTYPE enseignants SYSTEM "enseignants.dtd" >

<enseignants annÃ©e="2022">
    <enseignant dep="&dep;">
    <nom> Singer </nom>
    <prenom> Nicolas </prenom>
    </enseignant>
    <enseignant dep="&dep;">
    <nom> Trouilhet </nom>
    <prenom> Sylvie </prenom>
    <prenom> Marie </prenom>
    <age> 38 </age>
    </enseignant>
</enseignants>
