=== cgeorgy29/Git_FIA4/Corentin/SOA/TP/TP1/filmographie.dtd
<!ELEMENT films (film+)>
<!ELEMENT film (titre, exploitation, acteurs, durée, scénario)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT exploitation (dateSortie, nbEntrees, nbSalles, pays)>
<!ELEMENT dateSortie (#PCDATA)>
<!ELEMENT nbEntrees (#PCDATA)>
<!ELEMENT nbSalles (#PCDATA)>
<!ELEMENT pays (nomPays+)>
<!ELEMENT nomPays (#PCDATA)>
<!ELEMENT acteurs (acteur+)>
<!ELEMENT acteur (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT durée (#PCDATA)>
<!ELEMENT scénario (#PCDATA)>
<!ATTLIST film annéeSortie CDATA #REQUIRED>
<!ATTLIST film NdeVisa CDATA #IMPLIED>
<!ATTLIST durée unité CDATA #REQUIRED>

=== cgeorgy29/Git_FIA4/Corentin/SOA/TP/TP1/filmographie.xml
<!DOCTYPE films SYSTEM "filmographie.dtd">
<films>
    <film annéeSortie = "1994" NdeVisa ="75423">
        <titre>FORREST GUMP</titre>
        <genre>Comédie dramatique</genre>
        <réalisateur>Robert Zemeckis</réalisateur>
        <exploitation>
            <dateSortie>5 octobre 1995</dateSortie>
            <nbEntrees>3963919</nbEntrees>
            <nbSalles>334 </nbSalles>
            <pays>
                <nomPays>Belgique</nomPays>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>
                <nom>Hanks</nom>
                <prenom>Tom</prenom>
            </acteur>
            <acteur>
                <nom>Wright</nom>
                <prenom>Robin</prenom>
            </acteur>
            <acteur>
                <nom>Sinise</nom>
                <prenom>Gary</prenom>
            </acteur>
            <acteur>
                <nom>Filed</nom>
                <prenom>Sally</prenom>
            </acteur>
        </acteurs>
        <durée unité = "min">142 </durée>
        <scénario>Né fin des années 40 dans une bourgade du Sud, Forrest Gump est affecté d'un quotient intellectuel inférieur à la moyenne. Il livre à qui veut l'entendre l'étrange récit de sa vie, lui qui aura tout vu et tout fait sans comprendre ce qui lui arrivait, traversant et bouleversant en parfait candide près d'un demi-siècle d'histoire américaine.</scénario>
    </film>
    <film annéeSortie = "1999" NdeVisa="86423">
        <titre>La Ligne verte</titre>
        <genre>Drame</genre>
        <réalisateur>Franl Darabont</réalisateur>
        <exploitation>
            <dateSortie>1 Mars 2000</dateSortie>
            <nbEntrees>1714080</nbEntrees>
            <nbSalles>374</nbSalles>
            <pays>
                <nomPays>Belgique</nomPays>
                <nomPays>Suisse</nomPays>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>
                <nom>Hanks</nom>
                <prenom>Tom</prenom>
            </acteur>
            <acteur>
                <nom>Morse</nom>
                <prenom>David</prenom>
            </acteur>
            <acteur>
                <nom>Duncan</nom>
                <prenom>Michael Clarke</prenom>
            </acteur>
        </acteurs>
        <durée unité = "min">188</durée>
        <scénario>Paul Edgecomb, pensionnaire centenaire d'une maison de retraite, est hanté par ses souvenirs. Gardien-chef du pénitencier de Cold Mountain, en 1935, en Louisiane, il était chargé de veiller au bon déroulement des exécutions capitales au bloc E (la ligne verte) en s'efforçant d'adoucir les derniers moments des condamnés. Parmi eux se trouvait un colosse du nom de John Coffey, accusé du viol et du meurtre de deux fillettes.
        </scénario>
    </film>
    <film annéeSortie = "1986" NdeVisa="62200">
        <titre>Top Gun</titre>
        <genre>Action</genre>
        <réalisateur>Tony Scott</réalisateur>
        <exploitation>
            <dateSortie>17 septembre 1986</dateSortie>
            <nbEntrees>3570719</nbEntrees>
            <nbSalles>453</nbSalles>
            <pays>
                <nomPays>Angleterre</nomPays>
                <nomPays>Suisse</nomPays>
                <nomPays>Belgique</nomPays>
                <nomPays>Luxembourg</nomPays>
                <nomPays>Espagne</nomPays>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>
                <nom>Cruise</nom>
                <prenom>Tom</prenom>
            </acteur>
            <acteur>
                <nom>McGillis</nom>
                <prenom>Kelly</prenom>
            </acteur>
        </acteurs>
        <durée unité = "min">110</durée>
        <scénario>Jeune as du pilotage et tête brulée d'une école réservée à l'élite de l'aéronavale US ("Top Gun"), Pete Mitchell, dit "Maverick", tombe sous le charme d'une instructrice alors qu'il est en compétition pour le titre de meilleur pilote...</scénario>
    </film>
    <film annéeSortie = "2009" NdeVisa="102548">
        <titre>Avatar</titre>
        <genre>Science-Fiction</genre>
        <réalisateur>James Cameron</réalisateur>
        <exploitation>
            <dateSortie>16 décembre 2009</dateSortie>
            <nbEntrees>14775990</nbEntrees>
            <nbSalles>14 604</nbSalles>
            <pays>
                <nomPays>Irlande</nomPays>
                <nomPays>Pays-Bas</nomPays>
                <nomPays>Italie</nomPays>
                <nomPays>Espagne</nomPays>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>
                <nom>Worthington</nom>
                <prenom>Sam</prenom>
            </acteur>
            <acteur>
                <nom>Saldana</nom>
                <prenom>Zoe</prenom>
            </acteur>
            <acteur>
                <nom>Weaver</nom>
                <prenom>Sigourney</prenom>
            </acteur>
            <acteur>
                <nom>Lang</nom>
                <prenom>Stephen</prenom>
            </acteur>
        </acteurs>
        <durée unité = "min">162</durée>
        <scénario>Sur le monde extraterrestre luxuriant de Pandora vivent les Na'vi, des êtres qui semblent primitifs, mais qui sont très évolués. Jake Sully, un ancien Marine paralysé, redevient mobile grâce à un tel Avatar et tombe amoureux d'une femme Na'vi. Alors qu'un lien avec elle grandit, il est entraîné dans une bataille pour la survie de son monde.
        </scénario>
    </film>
    <film annéeSortie = "2011" NdeVisa ="152368">
        <titre>Drive</titre>
        <genre>Thriller</genre>
        <réalisateur>Nicolas Winding Refn</réalisateur>
        <exploitation>
            <dateSortie>5 octobre 2011</dateSortie>
            <nbEntrees>13536945</nbEntrees>
            <nbSalles>4235</nbSalles>
            <pays>
                <nomPays>Allemagne</nomPays>
                <nomPays>Espagne</nomPays>
                <nomPays>Italie</nomPays>
                <nomPays>USA</nomPays>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>
                <nom>Gosling</nom>
                <prenom>Ryan</prenom>
            </acteur>
            <acteur>
                <nom>Mulligan</nom>
                <prenom>Carey</prenom>
            </acteur>
            <acteur>
                <nom>Cranston</nom>
                <prenom>Bryan</prenom>
            </acteur>
        </acteurs>
        <durée unité = "min">95 </durée>
        <scénario>Né fin des années 40 dans une bourgade du Sud, Forrest Gump est affecté d'un quotient intellectuel inférieur à la moyenne. Il livre à qui veut l'entendre l'étrange récit de sa vie, lui qui aura tout vu et tout fait sans comprendre ce qui lui arrivait, traversant et bouleversant en parfait candide près d'un demi-siècle d'histoire américaine.</scénario>
    </film>
</films>
