<nuages>
    <nuage>
        <hydrometeore>oui</hydrometeore>
        <variete>Cumulonimbus</variete>
        <especes>
            <espece>calvus</espece>
            <espece>capilatus</espece>
            <espece type="gros">mamatus</espece>
        </especes>
        <altitudes>
            <min unite="m">300</min>
            <max unite="m">18000</min>
        </altitudes>
    </nuage>
    <nuage>
        <hydrometeore>non</hydrometeore>
        <variete>Altocumulus</variete>
        <especes>
            <espece>calvus</espece>
            <espece>lenticularis</espece>
            <espece>capilatus</espece>
            <espece type="gros">mamatus</espece>
        </especes>
        <altitudes>
            <min unite="m">500</min>
            <max unite="m">15000</min>
        </altitudes>
    </nuage>
</nuages>

<!DOCTYPE nuages [
    <!ELEMENT nuages (nuage)*>
    <!ELEMENT nuage (hydrometeore, variete, especes, altitudes)>
    <!ELEMENT hydrometeore (#PCDATA)>
    <!ELEMENT variete (#PCDATA)>
    <!ELEMENT especes (espece, espece, espece, espece)>
    <!ELEMENT espece (#PCDATA)>
    <!ELEMENT altitudes (#PCDATA)>
    <!ELEMENT min (#PCDATA)>
    <!ELEMENT max (#PCDATA)>
    <!ATTLIST espece type #PCDATA>
    <!ATTLIST 
        min unite #PCDATA
        max unite #PCDATA
        unite (m | km) "m">

    <!ATTLIST espece type CDATA #IMPLIED>
]>